defmodule Bendler.Gen do
  @moduledoc """
  Writes the shim: a Bend file whose `main` serves requests from the host
  through three foreign effects. `Bendler.fn` waits for the next request and
  answers its function index; `Bendler.arg` reads one argument of the type
  its spec spells; `Bendler.reply` writes the result back. The shim matches
  the index in `Bendler.step`, pulls the arguments, calls the user's def and
  replies. Every value crosses as a Base type the runtime lays out itself, so
  the C side never builds a user constructor.
  """

  alias Bendler.Sig

  @prelude_alias "BendlerPrelude"

  @doc "The shim source for the exports of the module at `import_path`; `prelude_path` is the prelude's, or nil."
  @spec shim(String.t(), [Sig.t()], String.t() | nil) :: String.t()
  def shim(import_path, sigs, prelude_path \\ nil) do
    arms =
      sigs
      |> Enum.with_index()
      |> Enum.map_join("\n", fn {sig, i} -> arm(sig, i) end)

    prelude = if prelude_path, do: "import #{prelude_path} as #{@prelude_alias}\n", else: ""

    """
    import Base
    import #{import_path} as M
    #{prelude}
    def Bendler.fn() -> IO(U32):
      import "./bendler_fn.c"
      import "./bendler_fn.js"

    def Bendler.arg(-A: Type, spec: String) -> IO(A):
      import "./bendler_arg.c"
      import "./bendler_arg.js"

    def Bendler.reply(-A: Type, spec: String, x: A) -> IO(Unit):
      import "./bendler_reply.c"
      import "./bendler_reply.js"

    def Bendler.step(fn: U32) -> IO(Unit):
      match fn:
    #{arms}
        case _:
          Bendler.reply(Unit, "!", Unit{})

    def Bendler.serve(fuel: Nat) -> IO(Unit):
      match fuel:
        case 0n:
          IO.pure(Unit, Unit{})
        case 1n+p:
          do IO<Unit>:
            fn : U32 <- Bendler.fn()
            Bendler.step(fn)
            Bendler.serve(p)

    def main() -> IO(Unit):
      Bendler.serve(4294967295n)
    """
  end

  defp arm(%Sig{name: name, params: params, ret: {ret_t, ret_text}}, i) do
    binds =
      Enum.map_join(params, "\n", fn p ->
        q = if p.reusable, do: "+", else: ""
        t = shim_type(p.text)

        "        #{q}#{p.name} : #{t} <- Bendler.arg(#{t}, #{inspect(Sig.spec(p.type))})"
      end)

    args = Enum.map_join(params, ", ", & &1.name)

    """
        case #{i}:
          do IO<Unit>:
    #{binds}
            Bendler.reply(#{shim_type(ret_text)}, #{inspect(Sig.spec(ret_t))}, M.#{name}(#{args}))\
    """
  end

  # the user's alias for the prelude's Bytes becomes the shim's
  defp shim_type(text),
    do: Regex.replace(~r/\b(?:\w+\.)?Bytes\b/, text, "#{@prelude_alias}.Bytes")

  @doc "Whether any export carries the prelude's Bytes."
  @spec uses_bytes?([Sig.t()]) :: boolean
  def uses_bytes?(sigs) do
    Enum.any?(sigs, fn s ->
      Enum.any?([elem(s.ret, 0) | Enum.map(s.params, & &1.type)], &has_bytes?/1)
    end)
  end

  defp has_bytes?(:bytes), do: true
  defp has_bytes?({:list, t}), do: has_bytes?(t)
  defp has_bytes?(_), do: false

  @doc "The per-module C header naming each export's argument and result specs."
  @spec specs_h([Sig.t()]) :: String.t()
  def specs_h(sigs) do
    args =
      Enum.map_join(sigs, ", ", fn s ->
        inspect(Enum.map_join(s.params, "", &Sig.spec(&1.type)))
      end)

    rets = Enum.map_join(sigs, ", ", fn %{ret: {t, _}} -> inspect(Sig.spec(t)) end)

    """
    // generated by bendler: the exports' type specs, in function-index order
    #define BENDLER_FN_COUNT #{length(sigs)}
    static const char* BENDLER_ARG_SPECS[] = { #{args}#{if sigs == [], do: "\"\"", else: ""} };
    static const char* BENDLER_RET_SPECS[] = { #{rets}#{if sigs == [], do: "\"\"", else: ""} };
    """
  end

  @doc "The NIF glue with the loading module's name filled in."
  @spec nif_glue(String.t(), module) :: String.t()
  def nif_glue(template, module) do
    String.replace(template, "BENDLER_MODULE", "Elixir." <> inspect(module))
  end

  @doc """
  Rewrites the emitted C for hosting inside the BEAM: `main` becomes
  `bend_main`, the runtime's signal handlers stay uninstalled (the VM owns
  them), and its `_exit` on a runtime error becomes `bendler_die`, which
  freezes the runtime instead of killing the VM.
  """
  @spec host_in_beam!(String.t()) :: String.t()
  def host_in_beam!(c_source) do
    patches = [
      {~r/^int main\(int argc, char\*\* argv\) \{$/m, "int bend_main(int argc, char** argv) {",
       1},
      {~r/^  sigaction\(SIG[A-Z]+, &sa, NULL\);$/m, "", 2},
      {~r/^  signal\(SIGPIPE, SIG_IGN\);$/m, "", 1},
      {~r/^  _exit\(1\);$/m, "  bendler_die(1);", 1}
    ]

    body =
      Enum.reduce(patches, c_source, fn {re, with, expected}, src ->
        found = length(Regex.scan(re, src))

        if found != expected do
          raise Bendler.Error,
                "the emitted C does not match this bendler: #{inspect(re.source)} found #{found} times, expected #{expected}"
        end

        String.replace(src, re, with)
      end)

    # nothing that seizes the process may survive the patching (exit stays
    # only in cli_fail, whose arguments bendler controls)
    survivors =
      Enum.flat_map(
        [~r/^\s*sigaction\(/m, ~r/^\s*signal\(/m, ~r/\b_exit\(/, ~r/^\s*abort\(/m],
        &Regex.scan(&1, body)
      )

    if survivors != [] do
      raise Bendler.Error,
            "the emitted C still calls #{inspect(survivors)} after patching; refusing to host it in the BEAM"
    end

    "void bendler_die(int code);\nint bend_main(int argc, char** argv);\n" <> body
  end
end
